### ISSUE TITLE
Zyra dragon sorceress, Texture question with the W

### ISSUE THREAD

**Issue by danielgamo354** [koobzaar/lol-skins#100]
As the title says, i have a question with the dragon sorceress zyra. I'm testing it on a practice tool, and the brightness of the 'W' when you place it is not the same as in a video.

When i put the W:
![saa](https://github.com/user-attachments/assets/48e0f325-61bc-4a7c-bad7-8f1abbb58c61)

The normal roots:
![sasasaa](https://github.com/user-attachments/assets/690145fd-fb88-4e3a-ba6d-a28fee57a71d)

And the roots that i see: (the roots of the passive are with the same brightness)
![aas](https://github.com/user-attachments/assets/ca1a257c-dc9d-489e-9dce-99d56d96a94e)

**Comment by koobzaar** [comment]
Not every skin are perfect - since ritoskin process almost 8000 skin. And we don't expect it to be perfect.

For minor issues like this simply isn't worth to take any effort to fix it - that's why we normally ignore. 

Hope you understand.
