### ISSUE TITLE
i need a hand to lend others a hand

### ISSUE THREAD

**Issue by ADAMM-kiwi** [koobzaar/lol-skins#11]
i have over +30 skins that is not in the skins available here i tried looking for yt videos to understand how to extract skins but i didnt find anything helpful anyone please help me i want to contribute to such a beautiful project !

**Comment by koobzaar** [comment]
@Ajacxx @darkdawn29 @LiseThistle

**Comment by Disgrace0310** [comment]
> i have over +30 skins that is not in the skins available here i tried looking for yt videos to understand how to extract skins but i didnt find anything helpful anyone please help me i want to contribute to such a beautiful project !

Not sure if you mean literally having them on your account? lol
If you have them that'd mean they're extracted already
To extract skins you don't need to own any of them, https://www.youtube.com/watch?v=tSGkz34Sf1c
this guide is a little outdated but you should be able to make it work if you follow the steps
