### ISSUE TITLE
[PROJECT Jhin] There are bugs in normal attacks

### ISSUE THREAD

**Issue by jinjutwo** [koobzaar/lol-skins#110]
![1734351506864](https://github.com/user-attachments/assets/b555519f-2a47-4eb2-92fa-578d927b6a96)

**Comment by vandi55** [comment]
[PROJECT Jhin.zip](https://github.com/user-attachments/files/18154462/PROJECT.Jhin.zip)
Fixed

**Comment by koobzaar** [comment]
@jinjutwo base or all chromas too?

**Comment by jinjutwo** [comment]
> base 还是 all chromas 也是？

Hello, all of them

**Comment by jinjutwo** [comment]
> base 还是 all chromas 也是？

Hello, all of them

**Comment by jinjutwo** [comment]
> [项目Jhin.zip](https://github.com/user-attachments/files/18154462/PROJECT.Jhin.zip)已修复

It's strange that I still have this bug after testing

**Comment by koobzaar** [comment]
Don't worry, I'll be recompiling all the skins by the end of the day.

**Comment by jinjutwo** [comment]
> 别担心，我会在一天结束前重新编译所有皮肤。
Okay, thank you very much

**Comment by koobzaar** [comment]
Should be fixed - the base skin and all chromas. Reopen this issue if you find any problems with it.
