### ISSUE TITLE
issue placing skins from folder lol skins

### ISSUE THREAD

**Issue by felokoko** [koobzaar/lol-skins#115]
when i place skin from your folder to cs lolmanager it s just doesn t show ingame no matter what i do

**Comment by nylish** [comment]
Begin by downloading the .zip file.  Next, open cslol, ensuring that you've located League of Legends.exe within your Riot Games folder.  Then, drag and drop the entire .zip file (not just the folder) into cslol, click run, enter practice tool mode, choose the default champion skin, and proceed with testing.
