### ISSUE TITLE
Missing skins? Skins crashing your game? Please comment the skin name here for manual review.

### ISSUE THREAD

**Issue by koobzaar** [koobzaar/lol-skins#12]
A large portion of skins in this repository is automatically generated, so some may have issues. These skins need manual review — extract them and re-add them to the repository after fixes. To track faulty skins, comment with the skin's name and the issue.

**Comment by koobzaar** [comment]
- [ ] Fix Battle Bunny Aurora

**Comment by koobzaar** [comment]
Aurora issue fixed by @darkdawn29 at #13

**Comment by koobzaar** [comment]
Heartsteel KSante is crashing the game when injected. Needs manual review.

**Comment by xunl2ealx** [comment]
I think Xin Zhao skins are missing.

**Comment by koobzaar** [comment]
> I think Xin Zhao skins are missing.

Fixed. Thanks!

**Comment by xunl2ealx** [comment]
Primordian Aatrox crashing.

**Comment by koobzaar** [comment]
@xunl2ealx fixed
