### ISSUE TITLE
some skins not working correct 

### ISSUE THREAD

**Issue by ut1lav** [koobzaar/lol-skins#14]
Heavenscale smolder has a white icon on minimap and hwei winterblessed isn't working (game crashing)

**Comment by ut1lav** [comment]
Risen legend leblanc doesn't work too

**Comment by koobzaar** [comment]
- [ ] Risen Legend Le'Blanc crashing fixed
- [ ] Hwei Winterblessed crashing fixed
- [ ] Heavenscale Smolder icon fixed
- [ ] HEARTSTEEL KSante crashing fixed
