### ISSUE TITLE
Wrong Kai'Sa skins

### ISSUE THREAD

**Issue by Abovz** [koobzaar/lol-skins#16]
Only Arcade, Bullet Angel, Star Guardian, Inkshadow are CORRECT the rest are chromas of Arcade and Lagoon Dragon Kai'Sa ;/

**Comment by Jugohugo** [comment]
pls fix this :(

**Comment by koobzaar** [comment]
I'm currently working on it.

I'm afraid that probably some others skins are wrong, too. Because there's no reason for only Kai'Sa skins doesn't match with the Data Dragon.

I'll keep you guys updated.

**Comment by koobzaar** [comment]
Apperently it's only with Kai'Sa skins (?)

**Comment by Jugohugo** [comment]
Yes, i see in the other folders, and this issue is just in the Kai'sa one

Em dom., 13 de out. de 2024, 14:41, Bruno Trigueiro <
***@***.***> escreveu:

**Comment by koobzaar** [comment]
Found the issue. Should be fixed in the next 5 min.

**Comment by koobzaar** [comment]
Please check if everything works fine now!

**Comment by Jugohugo** [comment]
So its fixed?

Em dom., 13 de out. de 2024, 15:13, Bruno Trigueiro <
***@***.***> escreveu:

**Comment by koobzaar** [comment]
@Jugohugo AFAIK, yes.
