### ISSUE TITLE
Skins that needs to be fixed

### ISSUE THREAD

**Issue by koobzaar** [koobzaar/lol-skins#17]
TODO:

- [x] Fix crashing issues with Risen Legend LeBlanc 
- [x] Fix crashing issues with  Hwei Winterblessed
- [x] Fix icon issues with Heavenscale Smolder
- [x] Fix crashing issues with  HEARTSTEEL KSante
- [x] Fix crashing issues with Battle Bat Xayah
- [x] Fix crashing issues with Battle Queen Fiora
- [x] Fix crashing issues with Fright Night Shaco

**Comment by Abovz** [comment]
battle bat xayah is crashing as well

**Comment by koobzaar** [comment]
Found the issue that caused all these skins to crash. Soon I'll be updating almost every .fantome file.
