### ISSUE TITLE
God King Garen Skins E Issue

### ISSUE THREAD

**Issue by SniteTheKing** [koobzaar/lol-skins#25]
As on all God King Garen Custom Skins, the E animation doesn't work (the Divine God King doesn't work either)

**Comment by koobzaar** [comment]
Moved to #21

**Comment by koobzaar** [comment]
Hello! We've investigated the problem and God King Garen doesn't have any relations to issue #27. But we know what the problem is and we are working on it too.

**Comment by nylish** [comment]
@SniteTheKing manual modification of the .bin file is required!
In the RitoSkin repo you have a tutorial how to change/adapt dagger for BQ Katarina ([Fix-Missing-Assets](https://youtu.be/DuEa4I8vLGk)). Take a look!
