### ISSUE TITLE
DJ Sona Sound not working

### ISSUE THREAD

**Issue by mFreack** [koobzaar/lol-skins#30]
I tried DJ Sona but sadly her ability sounds are not playing when using them.
Also her Voice Lines sound like there is a robot filter over it.

**Comment by nylish** [comment]
@mFreack manual modification of the .bin file is required!
In the RitoSkin repo you have a tutorial how to change/adapt dagger for BQ Katarina ([Fix-Missing-Assets](https://youtu.be/DuEa4I8vLGk)). Take a look!
