### ISSUE TITLE
Nightbringer yasuo sfx and animation

### ISSUE THREAD

**Issue by aurisdaug** [koobzaar/lol-skins#32]
there is some issues with the sfx of the skin, fixed the ult, because it played base vo when ulting and fixed the w sfx from base to the skin sfx, but the ult sfx and the animation is different
https://youtu.be/4ibWAzx3TZs?si=iRQI5epUpakaEIT6&t=268 seen in this video there arent any shadows that appear when ulting and no skin sfx on ult, been trying but i cant seem to figure it out

(P.S. The skin is all good no major errors, just a minor animation and sfx issue, can't really notice it, but will be nice of you if fixed.)

edit: https://www.mediafire.com/file/omox7285ta352mg/nb_yas_test_V1.0_by_UNKNOWN.fantome/file this is the download for the ult VO fix and w base to skin sfx if needed

**Comment by koobzaar** [comment]
This probably happens because our current implementation doesn't have the animation/ folder in any of our skins.

We don't have plans to fix it in the near future. But we will definitely work on it.

I'll keep this issue open for future revisions.


 Thanks!

**Comment by nylish** [comment]
@aurisdaug if you managed to solve the problem, open a PR with the .fantome skin! Thanks!
