### ISSUE TITLE
How do I use the files in the zips? I only know skins as .fantome and it won't let me drag and drop it into my skin manager! 

### ISSUE THREAD

**Issue by 1tatsumak1** [koobzaar/lol-skins#38]

**Comment by 1tatsumak1** [comment]
Nevermind I solved it I think, you just have to put the whole .zip into the skinloader. Thank you for your service guys.

**Comment by Jlopezg18** [comment]
what did you do? I'm not being able to use it.

**Comment by winstonlight0** [comment]
Hi, I used to move the fantome files to lolcustomskine and it worked, but now I'm starting to get errors, but I don't know how and with which application to run these zip files, please help?
![lolskin](https://github.com/user-attachments/assets/49590291-2900-4733-b0f8-380720bb2b19)

**Comment by koobzaar** [comment]
@winstonlight0 use the [2024-10-27-401067d](https://github.com/LeagueToolkit/cslol-manager/releases/tag/2024-10-27-401067d-prerelease) version

**Comment by winstonlight0** [comment]
> @winstonlight0 use the [2024-10-27-401067d](https://github.com/LeagueToolkit/cslol-manager/releases/tag/2024-10-27-401067d-prerelease) version

thanks bro

**Comment by FloppyFishCrisis** [comment]
![image](https://github.com/user-attachments/assets/0aad9290-270d-480d-8b03-387d805d5dab)

please help, this is not working from here

**Comment by koobzaar** [comment]
@FloppyFishCrisis did you extract everything? 

We can only answer questions based on the files themselves. We do not work on CSLOL or any injection-related tool.

**Comment by FloppyFishCrisis** [comment]
I just selected to zip file of the lol skins? Do I have to add them one by one?

**Comment by nylish** [comment]
> I just selected the zip file of the lol skins? Do I have to add them one by one?

Yes, you need to drop one by one.

**Comment by Jlopezg18** [comment]
no able to use it, any video?

**Comment by Jlopezg18** [comment]
<img width="739" alt="Captura de Pantalla 2024-11-14 a la(s) 4 50 59 p  m" src="https://github.com/user-attachments/assets/b1e68d0e-2ddf-433d-8d0b-b78d94b56a82">

**Comment by Enealol** [comment]
how can i install the mod

**Comment by Enealol** [comment]
and play on lol
