### ISSUE TITLE
God King Garen E Animation Issues

### ISSUE THREAD

**Issue by mb29g7** [koobzaar/lol-skins#41]
God King Garen and Fallen God King Gare both seem to have the same issue. When they press E, spin, their hands dont move and essentially stand still with the aura of the sword swinging. 

Hopefully people can fix it, happens in both skins. Other skins I tested were fine.
![image](https://github.com/user-attachments/assets/5a7369c4-8b48-4552-9e99-bb9ae30d7759)

**Comment by HarukazeKami** [comment]
this is a know bug, and we are working on a fix for it.

**Comment by koobzaar** [comment]
We actually don't know how to fix this 😕
