### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by winstonlight0** [koobzaar/lol-skins#44]
i, I used to move the fantome files to lolcustomskine and it worked, but now I'm starting to get errors, but I don't know how and with which application to run these zip files, please help?
![Uploading lolskin.PNG…]()

**Comment by martingeorgiev99** [comment]
which version of the loader are you running? new patch dropped today

[use this version](https://github.com/LeagueToolkit/cslol-manager/releases/tag/2024-10-27-401067d-prerelease)

**Comment by winstonlight0** [comment]
> which version of the loader are you running? new patch dropped today
> 
> [use this version](https://github.com/LeagueToolkit/cslol-manager/releases/tag/2024-10-27-401067d-prerelease)

yes I am using this new version

**Comment by winstonlight0** [comment]
> which version of the loader are you running? new patch dropped today
> 
> [use this version](https://github.com/LeagueToolkit/cslol-manager/releases/tag/2024-10-27-401067d-prerelease)

Thanks bro, my problem is solved.
