### ISSUE TITLE
Dawn Bringer Riven (as well as the chromas) Won't Hold the New Ult Model After Moving

### ISSUE THREAD

**Issue by Ianzami** [koobzaar/lol-skins#47]
Hi,

If you ult with Dawnbringer Riven (and either of its chromas), the new model is present but, if you then move, the model and and the sword revert to base form, only while casting R2 does it change back into the new model for a splits second.

**Comment by koobzaar** [comment]
Please check if it works fine. I've tried to reproduce your issue, but everything worked fine for me.
I recompiled just in case.
If it happens again, please submit an screenshot/ingame footage.

**Comment by Ianzami** [comment]
[https://i.imgur.com/OPeNnRK.gif](url) Here's a link of a gif of the problem, she doesn't stay in the ult form while moving and when she reverts back to it while standing still, the sword doesn't, and when moving again she loses the ult form until she stands still or uses R2
