### ISSUE TITLE
swain skin No language

### ISSUE THREAD

**Issue by yizhizhuguagua** [koobzaar/lol-skins#52]

**Comment by koobzaar** [comment]
Which Swain skin? Please be more descriptive.

**Comment by yizhizhuguagua** [comment]
Only two newly released ones have language

**Comment by yizhizhuguagua** [comment]
PROJECT: Gangplank E animation has bugs

**Comment by yizhizhuguagua** [comment]
tyrant swain ctrl+2 Animation has bugs

**Comment by koobzaar** [comment]
PROJECT: Gangplank was already fixed.

We don't have any plans to fix CTRL+2 animations - since it doesn't actually impact anything.
