### ISSUE TITLE
tyrant Swain Q Special effects lost

### ISSUE THREAD

**Issue by yizhizhuguagua** [koobzaar/lol-skins#59]
![fb9cb0c0f0258efd86df129b6d93c059](https://github.com/user-attachments/assets/160f9089-d704-453c-bedf-fba5edbda4df)
![image](https://github.com/user-attachments/assets/542a65db-1955-466e-89c8-905b4c474da7)

**Comment by koobzaar** [comment]
Thanks for reporting this issue. Upon investigation, I found that Swain's Q ability doesn't match your provided reference image, and there's another problem - the ability shows no particle textures when it doesn't connect with a target. While we attempted to fix this through recompilation, our program can't resolve this issue. This will require manual texture adjustments on the affected Swain skins.

感谢你报告这个问题。经过调查，我发现斯维因的 Q 技能与您提供的参考图像不匹配，并且还有另一个问题——当技能未命中目标时，没有显示任何粒子纹理。虽然我们尝试通过重新编译来修复，但我们的程序无法解决此问题。这需要对受影响的斯维因皮肤进行手动纹理调整。

**Comment by yizhizhuguagua** [comment]
https://github.com/user-attachments/assets/850c057e-8749-4b6f-ab10-2a3aa302b8a0

https://github.com/user-attachments/assets/78b2d7f4-0540-4219-ae97-c57d88dc360e

Compared to the original Q, it has lost a layer of special effects
