### ISSUE TITLE
Cosmic flight and divine phoenix anivia WALL WITHOUT TEXTURE

### ISSUE THREAD

**Issue by danielgamo354** [koobzaar/lol-skins#62]
the wall of the W of anivia cosmic flight don't have any texture
![anivia cosmic thing e bug](https://github.com/user-attachments/assets/d8821bc3-33bb-42f0-848c-51b7738bac91)

the wall of the divine phoenix has the same problem
![anivia phoenix w bug](https://github.com/user-attachments/assets/2a050f9a-8d66-40c3-9cdf-a7ae0dc64ec2)

**Comment by koobzaar** [comment]
We've long been aware that our software can't handle Anivia walls. As a result, every skin and chroma (except Victorious and Halloween Anivia) must be manually remade. Since this is unlikely to happen, we currently have no plans to address the issue.
