### ISSUE TITLE
[Primal Ambush Vi] Unavailable, error reported

### ISSUE THREAD

**Issue by 1411430556** [koobzaar/lol-skins#63]
Use the CSLO-Manager software to open the vi glitzy skin（Primal Ambush Vi），error reported

![image](https://github.com/user-attachments/assets/4d7f44db-24cd-4c65-9cea-35b5f1d4d369)

![image](https://github.com/user-attachments/assets/d0f2ff0f-6001-412b-ad84-05b9c2ced459)

Error message：
**backtrace: 
  lol::wad::Mounted::resolve_conflicts:
    this->relpath = WAD/Vi.wad.client
    other.relpath = WAD/Vi.wad.client
  lol::wad::Index::resolve_conflicts:
    this->name = Primal Ambush Vi 254047
    other.name = PsyOps Vi 254026
  mod_mkoverlay:
    src = ./installed
    dst = ./profiles/Default Profile
    game = D:/WeGameApps/英雄联盟/Game
error: Conflicting file: 0xdbabf4893177119d
name: Run mod-tools
version: 2024-10-27-401067d**

**Comment by koobzaar** [comment]
We are not developers of CSLOL. We don't have any relation to them. I'm sorry.

**Comment by 1411430556** [comment]
> We are not developers of CSLOL. We don't have any relation to them. I'm sorry.

Okay, that's okay. I've already solved the problem. Thank you
