### ISSUE TITLE
[Dawn Bringer Riven] During R, Model Reverts to Base Form While Moving and the Sword is Always the Base One

### ISSUE THREAD

**Issue by Ianzami** [koobzaar/lol-skins#64]
## Description
When Riven with the Dawnbringer skin (base or either of the 2 chromas) ults, the sword doesn't change to the R Model (complete sword and pink color) and while moving the model changes back to the base model.

## Affected Skin
- Skin Name: Dawnbringer Riven (and both chromas)

## Steps to reproduce 
1. Press R1 (notice that she changed form, sword being the base model)
2. Move, notice that the form reverts back to base
3. Stop moving, notice how the form reverts to ult form with the base sword
4. Move again, notice that the form reverts back to base
5. Hit R2 (Wing Slash), notice how the model changes to the correct ult model (minus the sword) then reverts back to base again instead of staying till the end of R1

## Expected Behavior
For her to hold the ult model for both herself and the sword for the whole duration of R, even while moving.

## Actual Behavior
While moving, she doesn't hold the ult model, and when stopping the model for the sword is still not being held to the ult one.

## Screenshots (optional, but very important)
https://i.imgur.com/K9GXIF5.gif - GIF

## Additional Details
- Custom Skin Application: Dawnbringer Riven (and both of its chromas)
- Custom Skin Application version: 1.0.0
- League of Legends Version: 14.22
- Operating System: Windows 11

**Comment by koobzaar** [comment]
Manually fixed.

**Comment by Ianzami** [comment]
Thanks
