### ISSUE TITLE
Primordian Aatrox Q's same after ult

### ISSUE THREAD

**Issue by kyxliexd** [koobzaar/lol-skins#66]
![resim_2024-11-15_235858069](https://github.com/user-attachments/assets/23a92774-7a01-45cd-b0ae-d5c938583678) 
With Ult (Normally)
![resim_2024-11-15_235932463](https://github.com/user-attachments/assets/e8e4ba34-c2f6-4ac4-a4c5-34426a8bb789) 
But this fantome after ult q's same without ult q's

**Comment by koobzaar** [comment]
Not fixable by Ritoskin. Needs manual extraction.

**Comment by kyxliexd** [comment]
> Not fixable by ritoskin. Needs manual extraction or a very specific fix. Since we have too many skins, we cannot change our software to fix a single issue. Someone can work on these skins manually if they want.

my friend said he can fix with visual studio code u can?

**Comment by koobzaar** [comment]
> my friend said he can fix with visual studio code u can?

If he can fix it, feel free to create a PR with the fix.
I only fix issues that can be resolved with RitoSkin. Due to the large number of skins, I won't focus on fixing specific skin attributes that require manual changes.
