### ISSUE TITLE
Radiant Wukong 

### ISSUE THREAD

**Issue by yike1a** [koobzaar/lol-skins#68]
OBS: We are a VERY diverse team. Feel free to write in your main language if it's better for you.

## Description
broken skin 
![image](https://github.com/user-attachments/assets/d7900d48-b9d3-43c0-a2a9-9d2d45aa4093)

**Comment by Enealol** [comment]
[yike1a](https://github.com/yike1a) vhow did you install the mod

**Comment by 0xJsoul** [comment]
does low graphics settings affect it or nah?

**Comment by koobzaar** [comment]
Working fine on both resolutions.
![Screen05](https://github.com/user-attachments/assets/40995f8f-d9d7-405b-ab49-b891aea3b06d)
![Screen06](https://github.com/user-attachments/assets/49db54d4-9deb-4a40-b62a-57c39b27b29b)
