### ISSUE TITLE
[True Damage Ekko] His background music is not playing

### ISSUE THREAD

**Issue by randevous-tp** [koobzaar/lol-skins#69]
True Damage Ekko has an exclusive background music that is playing all the time. His voice lines work properly and everything is good. Is it hard or just impossible to add his background music and make it work in tandem with his abilities?

**Comment by nylish** [comment]
If the background sound is a server-side feature, we can't do much about it.

**Comment by randevous-tp** [comment]
Are you  sure the background music from True Damage Ekko is server-sided and nothing can be done about it? DJ Sona and Seraphine Skins have no problem when playing their music. Tested other legendaries as well and seem that they have no problem. Is Ekko's background song coded weirdly or something? No way that his song is the only server-sided music . As i said, other skins have no issues as far as i have tested.
