### ISSUE TITLE
Added 2 chromas

### ISSUE THREAD

**Issue by Disgrace0310** [koobzaar/lol-skins#7]
I might be a little stupid as I can't figure out how to make a pull request lmao, here are the chromas
https://www.mediafire.com/file/n3319wob36e1fxx/Seadog_Yas_Rose_Quartz_V1.0_by_Disgrace0310.fantome/file
https://www.mediafire.com/file/ht5rbhf1j6rnvdt/Seadog_Yas_Pearl_V1.0_by_Disgrace0310.fantome/file

**Comment by koobzaar** [comment]
Don't worry. Thank you!

**Comment by koobzaar** [comment]
Don't worry. Thank you!
