### ISSUE TITLE
[Primordian Aatrox] Ult Red Effect

### ISSUE THREAD

**Issue by circus242** [koobzaar/lol-skins#75]
![Ekran Alıntısı](https://github.com/user-attachments/assets/ef097250-fd90-4c85-b3b1-2159149b1707)

**Comment by koobzaar** [comment]
Idk if its fixable, I'll take a look into it

**Comment by jinjutwo** [comment]
> 如果它是可修复的，我会看看

Hello, I am a League of Legends player from China, I want to get your private Exalted injection software, but I don't know how to donate, I want to donate to experience the software after getting it, and I also want more partners to experience it.

**Comment by koobzaar** [comment]
@jinjutwo 感谢您的留言。

在Ko-Fi平台上有一篇关于将'Exalted'移植到亚洲服务器（更具体地说是中国）的帖子。

由于英雄联盟在中国有不同的实现方式，我们正在研究'Exalted'是否能在中国运行。如需了解最新进展，请加入我们在readme文件或本GitHub仓库描述中提供的Discord群组，并通过私信告诉我您的昵称。

**Comment by jinjutwo** [comment]
> @jinjutwo 感谢您的留言。
> 
> 在Ko-Fi平台上有一篇关于将'Exalted'移植到亚洲服务器（更具体地说是中国）的帖子。
> 
> 由于英雄联盟在中国有不同的实现方式，我们正在研究'Exalted'是否能在中国运行。如需了解最新进展，请加入我们在readme文件或本GitHub仓库描述中提供的Discord群组，并通过私信告诉我您的昵称。

Thank you very much for your reply, because it is a cross-border reason, sometimes you can't open Ko-Fi, so I can't pay for donations, if I can, I want to make friends with you and learn from you, I'll leave you an email 627002155@qq.com

**Comment by jinjutwo** [comment]
> @jinjutwo 感谢您的留言。
> 
> 在Ko-Fi平台上有一篇关于将'Exalted'移植到亚洲服务器（更具体地说是中国）的帖子。
> 
> 由于英雄联盟在中国有不同的实现方式，我们正在研究'Exalted'是否能在中国运行。如需了解最新进展，请加入我们在readme文件或本GitHub仓库描述中提供的Discord群组，并通过私信告诉我您的昵称。

![dccafe608bb71617b4b7153472f4eed](https://github.com/user-attachments/assets/6d0f6c94-1596-4091-800c-365438ed40e5)
![19c2cb021cc9044b30fe4c00f62cbd9](https://github.com/user-attachments/assets/cc4323f6-fa1e-42e7-97ea-0f0a71c0c9b8)
Now I use this one, it works in China, and I really appreciate the skin you provided, I am confident that I have translated it into Chinese, so I want you to thank you again
