### ISSUE TITLE
[Risen Legend Ahri] W texture error

### ISSUE THREAD

**Issue by tunghay654** [koobzaar/lol-skins#78]
## Description
W texture is some square

## Affected Skin
- Skin Name: Risen Legend Ahri

https://github.com/user-attachments/assets/fda17589-d7bc-4cc9-8d91-b5245db4f87b

**Comment by WGPL777** [comment]
They know abt the issue, skin file just need to get recompiled again becaue league broke it again, so just gotta wait until kob will find free time and recompile her
