### ISSUE TITLE
Exalted Donated! How to access?

### ISSUE THREAD

**Issue by qiuham** [koobzaar/lol-skins#79]

**Comment by koobzaar** [comment]
You probably received an invite to our Discord server. Check your Ko-Fi.

**Comment by qiuham** [comment]
sry,i donate before sign kofi,can u send me again?
![image](https://github.com/user-attachments/assets/f70968cd-7019-4977-bcf3-885824908e31)

**Comment by koobzaar** [comment]
E-mail me with the payment details that you've used in Ko-Fi:

bruno.trigueiro@pm.me

**Comment by qiuham** [comment]
okay

**Comment by qiuham** [comment]
really appreciate

Bruno Trigueiro ***@***.***> 于2024年11月23日周六 18:58写道：
