### ISSUE TITLE
How to use the zip files?

### ISSUE THREAD

**Issue by discoveranytime** [koobzaar/lol-skins#80]
How do I get these files to work with CSLOL-Manager? Before this there were in .fantome format. Now in the folder they are META and WAD. I appreciate the sorting that has been done.

By the way thank you for doing this .fantome allows me to use any skin without injection. 💜

**Comment by WGPL777** [comment]
u just drop the zip file into cslol manager like normal fantome file

**Comment by discoveranytime** [comment]
Ohh okay bet thanks

**Comment by 0xJsoul** [comment]
Suggestion: Pin a 'How to Use' issue with how to use it and just refer to it.
