### ISSUE TITLE
God King or Fallen God King Garen E Ability not showing animations

### ISSUE THREAD

**Issue by Giehonne** [koobzaar/lol-skins#82]
OBS: We are a VERY diverse team. Feel free to write in your main language if it's better for you.

## Description
God King or Fallen God King Garen's E ability is bugged he is not spinning when E is casted and if you move it just plays his walking animations rather than his E animation with the double swords.

## Affected Skin
- Skin Name: God King Garen and Fallen God King Garen

## Steps to reproduce 
1. Just click E and the skins E animations are not played.

## Expected Behavior
He should be spinning with two swords while the E ability is casted.

## Actual Behavior
He is not spinning when the E ability is active the model is just standing and if you move it just plays his walking animations.

## Screenshots (optional, but very important)
[Please provide screenshots or screen recordings demonstrating the issue.]
![image_2024-11-25_015135838](https://github.com/user-attachments/assets/d9e12758-bc99-49e2-b146-4c3b20251e09)

## Additional Details
- Custom Skin Application: CSLOLMANAGER
- Custom Skin Application version: 2024-10-27-401067d
- League of Legends Version: 14.23.636.9832
- Operating System: Windows 10

## Logs or Error Messages (optional)
[If applicable, please provide any error messages or logs related to the issue.]

## Additional Context (optional)
[Add any other context about the problem that might be helpful for the maintainers to understand and resolve the issue.]
```

Key changes in this boilerplate:

1. **Affected Skin**: Asking the user to provide the specific skin name and version that is affected by the issue.
2. **Screenshots**: Explicitly requesting the user to provide screenshots or screen recordings to help demonstrate the issue.
3. **Additional Details**: Gathering more information about the user's setup, including the custom skin application, League of Legends version, and operating system.
4. **Logs or Error Messages**: Asking the user to provide any relevant error messages or logs related to the issue.
5. **Priority**: Allowing the user to suggest a priority level for the issue, which can help the maintainers understand the importance and urgency of the problem.

**Comment by koobzaar** [comment]
Duplicated #48
