### ISSUE TITLE
heimerstinger, problem with her E

### ISSUE THREAD

**Issue by danielgamo354** [koobzaar/lol-skins#83]
There is an issue with Heimerdinger's skin where when the E explodes, a square appears (this doesn't happen in the evolved form).

https://github.com/user-attachments/assets/fab6e316-7ffb-4226-8d54-58055a5b298d

**Comment by koobzaar** [comment]
Heimerstinger, Three Honors Akshan skin (#56, #77) and several others consistently have issues with new patches. I'll recompile them and monitor for problems in the next update.

**Comment by koobzaar** [comment]
@danielgamo354 also thanks from always being an active person on lol-skins and bringing us the issues with the skin since the beggining. If you don't have Exalted, feel free do e-mail me to get a free copy.

**Comment by danielgamo354** [comment]
Hi, thank you for uploading all the skins, i searched this like for 1 week,
and when i find the github page i wanted to test all the skins and i am
also doing this right now, i`m on heimerdinger, but i will see the rest. If
you want to send the free copy send me, i don't know that is it but i will
thank you,

Also if you want to text me when you repair some skins, or maybe if riot
get out other update that broke again the skins, or whatever you want to
test it, i can do it without problem

**Comment by nylish** [comment]
@danielgamo354 add me on discord: nylish.me

**Comment by danielgamo354** [comment]
done
