### ISSUE TITLE
[Immortel Journey Kayle 10059]  have a big big Blue square in the Recall Animation

### ISSUE THREAD

**Issue by ThisVanessa** [koobzaar/lol-skins#87]
![Screenshot 2024-11-26 162041](https://github.com/user-attachments/assets/1e882240-5ba4-4db5-8059-090fdee85dcb)

## Description
 have a big big Blue square in the Recall Animation

## Affected Skin
- Skin Name: Immortel Journey Kayle 10059

**Comment by koobzaar** [comment]
We are aware of it and we are working on a solution.
Thank you!
