### ISSUE TITLE
[True Damage Ekko] Background Music Not Playing

### ISSUE THREAD

**Issue by randevous-tp** [koobzaar/lol-skins#88]
His background music is not playing. DJ Sona and Seraphine Skins have no problem when playing their music. Tested other legendaries that have music and they have no problem. Is Ekko's background song coded weirdly or something? No way that his song is the only server-sided music . As i said, other skins have no issues.

**Comment by Ecclesiastes1-9** [comment]
Recompiled. Please check if it works now.

**Comment by randevous-tp** [comment]
Nah, it doesnt work. Let me be clear, i didnt speak about his recall music. Im speaking about his background music that plays all the time (the song Giants) which syncs with abilities. I tried original True Damage Ekko, the song doesnt play in the background... After that i tried a few of his chromas and it still doesnt play. I even tried Breakout True Damage/ Still doesnt work.

**Comment by randevous-tp** [comment]
Nah. Doesnt work. Tried his og skin, his chromas and even the Breakout True
Damage version. His background music doesnt play/
