### ISSUE TITLE
[Soul Fighter Samira] Minion kill VFX missing

### ISSUE THREAD

**Issue by cazaraaaa** [koobzaar/lol-skins#89]
OBS: We are a VERY diverse team. Feel free to write in your main language if it's better for you.

## Description
As I saw in a skin spotlight video (i'll put the link here) when you kill a minion there's supposed to be a special vfx for its death, which is not present when using the skin.

## Affected Skin
- Skin Name: [Soul Fighter Samira]

## Steps to reproduce 
1. just kill a minion with range and melee attack and you'll see
2. i was level 7 during the video, but it occurs when level 18 too

## Expected Behavior
the vfx being like the skin spotlight video (https://www.youtube.com/watch?v=3eevSLfSsaM&t=114s)

## Actual Behavior
the minion just dies normally without any vfx

## Screenshots (optional, but very important)
the video is too big so here's mediafire link (sorry) : https://www.mediafire.com/file/534ebts3o3rmvzy/2024-11-28_22-50-26.mp4/file

## Additional Details
- Custom Skin Application: cslol manager
- Custom Skin Application version: 2024-10-27-401067d
- League of Legends Version: 14.23.6369832+branch.releases-14-23.code.public.content.release.anticheat.vanguard
- Operating System: Windows 11

Key changes in this boilerplate:

1. **Affected Skin**: Asking the user to provide the specific skin name and version that is affected by the issue.
3. **Screenshots**: Explicitly requesting the user to provide screenshots or screen recordings to help demonstrate the issue.
4. **Additional Details**: Gathering more information about the user's setup, including the custom skin application, League of Legends version, and operating system.
5. **Logs or Error Messages**: Asking the user to provide any relevant error messages or logs related to the issue.
6. **Priority**: Allowing the user to suggest a priority level for the issue, which can help the maintainers understand the importance and urgency of the problem.

**Comment by Kyorzo** [comment]
battle queen kata has no daggers btw

**Comment by Ecclesiastes1-9** [comment]
Recompiled. Please check if it works now.
