### ISSUE TITLE
[Arcane Enemy Jinx] Jinx new skin

### ISSUE THREAD

**Issue by jinjutwo** [koobzaar/lol-skins#95]
After testing, Jinx's new skin is still the same

**Comment by Ianzami** [comment]
There are two Arcane skins in the Jinx folder but both are the same, the new skin is called Arcane Fractured Jinx, doesn't seem to have been added yet

It would be cool if we could at least get the Hooded form extracted and working as it's basically a legendary skin

**Comment by jinjutwo** [comment]
> Jinx 文件夹中有两个 Arcane 皮肤，但都是一样的，新皮肤叫 Arcane Fractured Jinx，似乎还没有添加
> 
> 如果我们至少能提取 Hooded 形式并正常工作，那就太酷了，因为它基本上是一个传奇皮肤

Yes, I also found that the effect is the same for both skins

**Comment by ThisVanessa** [comment]
There are problems with the Arcane Fractured Jinx which is probably why it is being used as a placeholder. Please be patient.

**Comment by jinjutwo** [comment]
> 奥术断裂金克丝存在问题，这可能就是它被用作占位符的原因。请耐心等待。

OK
