### ISSUE TITLE
Ambitious Elf Jinx Skin Issue

### ISSUE THREAD

**Issue by fwicotex** [koobzaar/lol-skins#99]
## Description
Rocket on ultimate is bugged and shows a big square.

## Affected Skin
- Skin Name: Ambitious Elf Jinx

## Steps to reproduce 
1. Press R

## Expected Behavior
Have a normal R animation

## Actual Behavior
Shows a big square instead of the rocket

## Screenshots (optional, but very important)
![image](https://github.com/user-attachments/assets/71838011-42e0-43a8-bd0f-ec39b9f072ef)

**Comment by koobzaar** [comment]
Recompiled. Please check if it is fixed. If not, re-open the issue.
